apiVersion: v2
name: garage
description: Garage deployment for TrueNAS SCALE

type: application

home: https://garagehq.deuxfleurs.fr
icon: https://garagehq.deuxfleurs.fr/images/garage-logo.svg

version: 0.9.3
appVersion: "0.9.3"
